version: "3.8"
services:

  app:
    build: .
    command: sh -c "npm start"
    ports: 
      - "4000:4000"
    volumes: 
      - .:/usr/app
    links: 
      - db
    depends_on: 
      - db
      
  db:
    image: postgres:9.4
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  db-data:

networks:
  overlay: